# Generated by Django 3.0.8 on 2021-01-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contactmeinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmeinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
